archive_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('pages.urls')),
]

pages/urls.py
from django.urls import path, include
from django.conf.urls import url, include

from . import views

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    #url(r'^result/$', views.search, name='result'),
    path('projects/<uuid:ext_id>/', views.ProjectDetailView.as_view(), name='rsprojects'),
    # path('alumni_tree/', views.AlumniTreePageView.as_view(), name='alumni_tree'),
    path('browse/', views.BrowseView.as_view(), name='browse'),
    path('search/', views.search, name='search'),
    # url(r'^search/$', views.search, name='search'),
] 

pages/models.py
from django.db import models
import uuid

class Author(models.Model):
    ### DATABASE FIELDS
    full_name = models.CharField(max_length=45, primary_key=True)
        
    ### TO STRING METHOD
    def __str__(self):
        return self.full_name
        
class Project(models.Model):
    ### CHOICES
    DIVISIONS = (
        ('SOCI', 'Social & Behavioral Sciences'),
        ('BUSI', 'Business & Computing'),
        ('CONS', 'Consumer & Health Sciences'),
        ('CULI', 'Culinology & Food Science'),
        ('HOSP', 'Hospitality, Travel & Tourism'),
        ('KINE', 'Kinesiology & Athletics'),
        ('NUTR', 'Nutrition & Dietetics'),
        ('MATH', 'Mathematics & Sciences'),
        ('LITE', 'Literature & Languages'),
        ('TECH', 'Technology'),
        ('VISU', 'Visual & Performing Arts'),
    )

    FORMAT = (
        ('POS', 'Poster Session'),
        ('ORA', 'Oral Presentation'),
        ('EXH', 'Exhibition of Work'),
    )

    ### DATABASE FIELDS
    title = models.CharField(max_length=255)
    division = models.CharField('Division', max_length=4, choices=DIVISIONS)
    tagline = models.TextField()
    mentor = models.TextField()
    year = models.IntegerField()
    presentation_format = models.CharField('Presentation Format', max_length=3, choices=FORMAT)
    abstract = models.TextField()
    paper = models.TextField(blank = True)
    cited_source = models.TextField(blank = True)
    drive_folder_link = models.CharField(max_length=255, blank = True)
    
    ext_id = models.UUIDField(default=uuid.uuid4, editable=False)
    ### MODEL RELATIONSHIP(S)
    author = models.ManyToManyField(Author, db_table="result")

    ### TO STRING METHOD
    def __str__(self):
        return self.title
    

pages/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView
from django.views.generic.detail import DetailView
from django.http import JsonResponse
from django.urls import reverse
from pages.models import Project, Author

from django.db.models import Q

class HomePageView(TemplateView):
    """View to display Home Page"""
    template_name = 'home.html'
    model = Project, Author

class BrowseView(TemplateView):
    """View to display Browse Page"""
    template_name = 'browse.html'
    def get_queryset(self):
        """Fetch queryset and pass to `ajax_search.html`. Taking in query, search-by terms,
        (optionally categories using Sidebar). Filter using `icontanins`."""
        return search(self)

class ProjectDetailView(DetailView):
    """View to display project details"""
    template_name = 'projects.html'
    context_object_name = 'project'
    model = Project
    
    # Read UUID into Slug Field to accomodate DetailView 
    slug_field = 'ext_id'
    slug_url_kwarg = 'ext_id'

def search(request):
    """Fetch queryset and pass to `ajax_search.html`. Taking in query, search-by terms,
    (optionally categories using Sidebar). Filter using `icontanins`."""
    if 'q' in request.GET and request.GET['q']:
        q = request.GET['q']
        s = request.GET['s']
    else:
        q = ''
        s = request.GET['s']
        projects = Project.objects.filter(tagline__icontains=q)
    if s == 'all':
        title = Project.objects.filter(title__icontains=q)
        tagline = Project.objects.filter(tagline__icontains=q) 
        author = Project.objects.filter(author__full_name__icontains=q)
        mentor = Project.objects.filter(mentor__icontains=q)

        projects = title | tagline | author | mentor
    elif s == 'title':
        projects = Project.objects.filter(title__icontains=q)         
    elif s == 'author':
        projects = Project.objects.filter(author__full_name__icontains=q)         
    elif s == 'mentor':
        projects = Project.objects.filter(mentor__icontains=q)         
    elif s == 'tagline':
        projects = Project.objects.filter(tagline__icontains=q)  
    cat = request.GET.get('cat', '').split(',')
    if (cat != ['']): 
        temp = projects & Project.objects.filter(tagline__icontains=cat[0])
        for c in cat:
            temp = temp | (projects & Project.objects.filter(tagline__icontains=c))
        projects = temp
    return render(request, 'ajax_search.html', {'projects': projects.distinct()})
    

templates/ajax_search.html
{% load string_format %}
{% if projects %}
    <div class="row align-items-center py-2">
      <div class="col-auto mr-auto"><p>{{ projects.count }} project(s)</p></div>
    </div>
    
    <!-- Table -->
    <div class="table-responsive">
      <table class="table table-striped table-responsive table-hover">
        <thead>
          <tr>
              <th scope="col" style="vertical-align: middle;"><a>Author(s)</a></th>
              <th scope="col" style="vertical-align: middle;"><a>Project Title</a></th>
              <th scope="col" style="vertical-align: middle;"><a>Division</a></th>
              <th scope="col" style="vertical-align: middle;"><a>Mentor(s)</a></th>
              <th scope="col" style="vertical-align: middle; min-width: 4.8rem;"><a>Year</a></th>
            <th scope="col" ><a>Presentation Format</a></th>
          </tr>
        </thead>
        <tbody>
          <form action="/browse/" method="get">
          {% for project in projects %}
            <tr>
              <td>
                <a href="/browse/?q={{ project.author.all.0.full_name|string_format }}&s=author">
                  {{ project.author.all.0.full_name }}</a>
                {% for author in project.author.all %}
                    {% if forloop.counter > 1 %}
                    , <a href="/browse/?q={{ author.full_name|string_format }}&s=author">{{ author.full_name }}</a>
                    {% endif %}
                {% endfor %}
              </td>
              <td><a href="{% url 'rsprojects' project.ext_id %}">{{ project.title }}</a></td>
              <td>{{ project.get_division_display }}</a></td>
              <td>{{ project.mentor }}</td>
              <td>{{ project.year }}</td>
              <td>{{ project.get_presentation_format_display }}</td>
            </tr>
            {% endfor %}
          </form>
        </tbody>
    </table>
    </div>
{% else %}
<p>No project matched your search criteria</p>
{% endif %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    
    {% load static %}
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
    <!-- Our Custom CSS, static file -->
    <link rel="stylesheet" type="text/css" href="{% static 'pages/css/style.css' %}">
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">
    <!-- Icon Supply via Google Web Fonts -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    
  </head>

<body>
    <!-- Navbar-->
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 bg-white border-bottom box-shadow">
        <a class="my-0 mr-md-auto font-weight-normal" href="/">
            <img src="{% static 'pages/images/logo_2.png' %}" alt="logo" style="max-height: 2rem; max-width: auto;">
        </a>
        <nav class="my-2 my-md-0 mr-md-3">
            <a class="p-4 nav-text" href="/">Home</a>
            <a class="p-4 nav-text" href="/browse/">Browse projects</a>
            <a class="p-4 nav-text" href="/#about">About us</a>
            <a class="p-4 nav-text" href="/#contact">Contact</a>
        </nav>
      </div>
        {% block content %}
        {% endblock %}

    <!-- jQuery CDN -->
    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <!-- Popper.JS -->      
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    <!-- jQuery Custom Scroller CDN -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>    
    <!-- Ajax -->
    <script src="{% static 'js/ajax.js' %}"></script>
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    
    {% load static %}
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">

    <!-- Custom static style -->
    <link rel="stylesheet" type="text/css" href="{% static 'pages/css/style.css' %}">

    <!-- Icon Supply via Google Web Fonts -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

    <!-- Title -->
    <title>Archiver Project | Student Project and Research Symposium Club</title>

</head>

<body>
    <!-- Navbar-->
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
        <a class="my-0 mr-md-auto font-weight-normal">
        </a>
        <nav class="my-2 my-md-0 mr-md-3">
            <a class="p-4 nav-text" href="/">Home</a>
            <a class="p-4 nav-text" href="/browse/">Browse projects</a>
            <a class="p-4 nav-text" href="/#about">About us</a>
            <a class="p-4 nav-text" href="/#contact">Contact</a>
        </nav>
      </div> <!-- END Navbar -->

    <div style="height: 620px;">
        <img class="cover-bg img-fluid" src="{% static 'pages/images/bg_1.png' %}">

        <!-- Search -->
        <div>
            <div class="home-center home-gray-block" style="opacity: .59; "></div>
            <div class="home-center col mx-auto d-block" id="logo-search">
                <img class="img-fluid mx-auto d-block mb-4 pt-5" src="{% static 'pages/images/logo_1.png' %}" alt="logo" style="max-height: 8.5rem; max-width: auto;">
                    
                <!-- Search Form -->
                <form action="/browse/" method="get">
                    <div class="form-row px-3">
                        <div class="form-group col-md-10 reduce-spacing">
                            <label for="searchInput"></label>
                            <input name="q" id="searchInput" type="text" placeholder="Search..." class="form-control custom-form shadow-lg" aria-label="Search">
                        </div>
                        <div class="form-group col-md-2 custom-form">
                            <label for="searchFieldSelect"></label>
                            <select name="s" id="searchSelect" class="form-control custom-form shadow-lg">
                                <option selected value="all">All fields</option>
                                <option value="title">Title</option>
                                <option value="author">Author</option>
                                <option value="mentor">Mentor</option>
                                <option value="tagline">Keywords</option>
                                
                            </select>
                        </div>
                    </div>
                </form> <!-- END Search Form -->

                <div class="container pt-4">
                    <a href="/browse/" class="underline-text text-light">or browse projects here</a>
                </div> 
            </div>
        </div>  <!-- END Search -->

        <a href="#about" class="mx-auto d-block btn btn-xl btn-circle btn-light shadow-lg mt">
            <i class="fas fa-chevron-down " style="color: #848484;"></i>
        </a>
    </div>

    <div class="bg-light position-relative"> 
        <div id="home-decor-block-1"></div>
        <!-- About Us -->
        <div class="container py-5 px-5" id="about">
            <div class="row">
                <div class="col-md-7">
                    <h1>About us</h1>
                    <div class="deco-layout-block"></div>
                    <p>We’re the Student Project and Research Symposium Club of Orange Coast College. As a community of aspired researchers and developers who are actively participating in OCC’s annual research symposium, we set out to promote and fortify the student research community of OCC with resources and workshops, namely peer review sessions, presentation mock-ups, networking parties, etc.</p>
                    <p>This website serves as an archive of past symposium projects and researches which have been granted display permission by their rightful creators. We hope you find this website to be an useful tool to jumpstart your very own project and get a feel of the standards for OCC symposium submissions.</p>
                    <p>If you wish to acquire contacts of a listed researcher or have any lingering question, worry, feel free to send us an email as we’re more than happy to help. We are also open to collaboration and recruits. For more information, please contact us via the address below.</p>
                </div>
                <div class="col-md-5 d-none d-md-block pt-5">
                    <img class="h-75" src="{% static 'pages/images/science_1.png' %}" alt="Picture Of Scientific Reseach">
                </div>
            </div>
        </div> <!-- END About Us -->

        <div class="dark-line"></div>

        <!-- Footer -->
        <footer id="contact">
            <div class="container container text-center pb-2 pt-4">
                <p>Contact via <a href="mailto:occsparsclub@gmail.com">occsparsclub@gmail.com</a></p>
                <p>
                <a href="#">Back to top</a>
                </p>
            </div>
        </footer> <!-- END Footer -->
    </div>

    <!-- jQuery first, then Popper.js, then Bootstrap JS-->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

templates/projects.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title></title>
</head>
<body>
    {% extends 'base.html' %}
    {% block content %}
    <div>
        <div class="container pt-5 px-3">
        <div class="container px-4">
            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-4 mb-3 border-bottom border-secondary">
                <h4>{{ object.title }}</h4>
            </div>
        </div>
                
            <table class="container table table-borderless table-sm mt-4">
                <tr class="row">
                    <td class="px-5 col-4"><strong>Division: </strong></td>
                    <td class="col-8">{{ object.get_division_display }}</td>
                </tr>
                <tr class="row">
                    <td class="px-5 col-4"><strong>Author(s): </strong></td>
                    <td class="col-8">
                        {% for author in project.author.all %}
                            {{ author.full_name }}
                        {% endfor %}
                    </td>
                </tr>
                <tr class="row">
                    <td class="px-5 col-4"><strong>Mentor(s): </strong></td>
                    <td class="col-8">{{ object.mentor }}</td>
                </tr>
                <tr class="row">
                    <td class="px-5 col-4"><strong>Year: </strong></td>
                    <td class="col-8">{{ object.year }}</td>
                </tr>
                <tr class="row">
                    <td class="px-5 col-4"><strong>Presentation Format: </strong></td>
                    <td class="col-8">{{ object.get_presentation_format_display }}</td>
                </tr>
                <tr class="row">
                        <td class="px-5 col-4"><strong>Cited Sources: </strong></td>
                        <td class="col-8">{{ object.cited_source }}</td>
                    </tr>
                <tr class="row">
                    <td class="px-5 col-4"><strong>Tags: </strong></td>
                    <td class="col-8">{{ object.tagline }}</td>
                </tr>
                <tr class="row">
                    <td class="px-5 col-4"><strong>Slides/poster: </strong></td>
                    <td class="col-8"><a href="{{ object.drive_folder_link }}">See more</a></td>
                </tr>
                <tr class="row">
                    <td class="px-5 col-12">
                        <strong>Abstract:</strong>
                        <p>{{ object.abstract|linebreaks }}</p>
                    </td>
                </tr>
            </table>
            
            <div class="container mx-3 my-5">                
                <p class="my-3"></p>
            </div>

        </div>
    </div>
    {% endblock %}
</body>
</html>